Adding retry for acceptance if fails

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -112,7 +112,16 @@ jobs:
 
     - name: Run acceptance tests
       run: |
-        bundle exec rake 'litmus:acceptance:parallel'
+        for i in 1 2 3; do
+          if bundle exec rake 'litmus:acceptance:parallel'; then
+            break
+          elif [ "$i" -lt 3 ]; then
+            echo "Retrying acceptance tests (Attempt $i)"
+          else
+            echo "Acceptance tests failed after $i attempts."
+            exit 1
+          fi
+        done
 
     - name: Remove test environment
       if: ${{ always() }}
